FROM mcr.microsoft.com/playwright:focal

RUN apt update

RUN apt install -y libnss3-tools 

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


RUN useradd -m -s /bin/bash linuxbrew && \
    echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

USER root

RUN apt install -y build-essential curl file
ENV LINUXBREWHOME=/home/linuxbrew/.linuxbrew
ENV PATH=$LINUXBREWHOME/bin:$PATH
ENV PKG_CONFIG_PATH=$LINUXBREWHOME/lib64/pkgconfig:$LINUXBREWHOME/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=$LINUXBREWHOME/lib64:$LINUXBREWHOME/lib:$LD_LIBRARY_PATH

RUN brew install mkcert

COPY . .

RUN mkdir -p $HOME/.pki/nssdb
RUN certutil -d sql:$HOME/.pki/nssdb -N --empty-password

ENV CAROOT="/usr/src/app/.cert"

RUN mkcert -install

WORKDIR /usr/src/app

CMD [ "npm", "test" ]